import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import favicon from "./favicon.ico";
import Nav from "./_components/nav";
import AuthProvider from "./context/AuthProvider";
import QueryProvider from "./utlis/provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import StoreProvider from "./utlis/store-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: ` ${siteConfig.name}`,
  },
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
const myFavicon = favicon.src;

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={myFavicon} />
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AuthProvider>
                <div>
                  <Nav />
                  <NextSSRPlugin
                    routerConfig={extractRouterConfig(ourFileRouter)}
                  />
                  <Toaster />
                  {children}
                  {modal}
                </div>
              </AuthProvider>
            </ThemeProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
