// "use client";
import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";
import { AiOutlineArrowRight } from "react-icons/ai";
import { GiSoccerField } from "react-icons/gi";
import Toast from "./_components/toast";

export const metadata: Metadata = {
  title: "Arena Spotter",
  description: "Generated by create next app",
};

const ParentComponent = () => {
  return (
    <div className="flex flex-col items-center justify-center text-center h-[70vh]">
      <h2 className="text-9xl">
        <GiSoccerField className="text-9xl" />
      </h2>

      <h1 className="text-4xl font-extrabold">Search arenas near you</h1>
      <h3 className="text-xl text-zinc-400 w-[700px] my-4">
        Beautifully designed components that you can copy and paste into your
        apps. Accessible. Customizable. Open Source. Get Started GitHub
      </h3>
      <Link href={"/arena"}>
        <Button className="flex gap-1 hover:gap-2">
          Arenas
          <AiOutlineArrowRight />
        </Button>
      </Link>

      {/* <Toast
        title={"Scheduled: Catch up"}
        description={"Friday, February 10, 2023 at 5:57 PM"}
        variant={"success"}
      />
      <Toast
        title={"działam"}
        description={"Edward sinooo"}
        variant={"error"}
      /> */}
      {/* <UploadBtn /> */}
    </div>
  );
};

export default ParentComponent;
